repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix", "--no-sort-keys"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==21.3.1']
- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
    - id: black
      types: [python]
      language_version: python3
- repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
  hooks:
    - id: isort
      types: [python]
      language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v2.10.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
